//production
//  export const protocol_http = window.location.protocol+'//';
//  export const domain_credmgr = window.location.host;
module.exports = {
  Project_Name: "ProjectName",
  Project_Customer: "ProjectCustomer",
  Project_Owner: "ProjectOwner",
  Last_Modified_Date: "LastModifiedDate",
  Project: "Project",
  Customer: "Customer",
  Project_ID: "ProjectID",
  LOCALE_SET_STARTED: "LOCALE_SET_STARTED",
  LOCALE_SET_FULFILLED: "LOCALE_SET_FULFILLED",
  LOCALE_SET_FAILED: "LOCALE_SET_FAILED",
  UPDATE_MESSAGES: "UPDATE_MESSAGES",

  //Notifications action types
  SHOW_SUCCESS_NOTIFICATION: "SHOW_SUCCESS_NOTIFICATION",
  SHOW_ERROR_NOTIFICATION: "SHOW_ERROR_NOTIFICATION",
  SHOW_WARNING_NOTIFICATION: "SHOW_WARNING_NOTIFICATION",
  SHOW_INFO_NOTIFICATION: "SHOW_INFO_NOTIFICATION",
  HIDE_NOTIFICATION: "HIDE_NOTIFICATION",

  //project list action types
  FETCH_PROJECTLIST_START: "FETCH_PROJECTLIST_START",
  FETCH_PROJECTLIST_FULFILLED: "FETCH_PROJECTLIST_FULFILLED",
  FETCH_PROJECTLIST_FAILED: "FETCH_PROJECTLIST_FAILED",
  NEED_PROJECTLIST_REFRESH: "NEED_PROJECTLIST_REFRESH",
  UPDATE_PROJECT_GRID_STATE: "UPDATE_PROJECT_GRID_STATE",
  UPDATE_PROJECT_GRID_TAb: "UPDATE_PROJECT_GRID_TAb",

  //Add selection dropdown action types
  UPDATE_BUILDER_LIST_WITH_PERMISSION: "UPDATE_BUILDER_LIST_WITH_PERMISSION",
  UPDATE_ALL_BUILDER_ROUTES: "UPDATE_ALL_BUILDER_ROUTES",

  CUSTOMER_DETAILS_LOADING: "CUSTOMER_DETAILS_LOADING",
  CUSTOMER_DETAILS_LOADED: "CUSTOMER_DETAILS_LOADED",
  CUSTOMER_DETAILS_LOADING_FAILED: "CUSTOMER_DETAILS_LOADING_FAILED",

  //project detial list action types
  FETCH_PROJECTDETAILLIST_START: "FETCH_PROJECTDETAILLIST_START",
  FETCH_PROJECTDETAILLIST_FULFILLED: "FETCH_PROJECTDETAILLIST_FULFILLED",
  RESET_PROJECTDETAILLIST: "RESET_PROJECTDETAILLIST",
  FETCH_PROJECTDETAILLIST_FAILED: "FETCH_PROJECTDETAILLIST_FAILED",

  //update tag action types
  SAVETAG_START: 'SAVETAG_START',
  SAVETAG_FULFILLED: 'SAVETAG_FULFILLED',
  SAVETAG_FAILED: 'SAVETAG_FAILED',

   //Get template list
  GET_TEMPLATE_LIST_FULFILLED: "GET_TEMPLATE_LIST_FULFILLED",
  GET_TEMPLATE_LIST_FAILED: "GET_TEMPLATE_LIST_FAILED",

  //Get tag list
  CLEAR_TAG_LIST: "CLEAR_TAG_LIST",
  REFRESH_TAG_GRID: "REFRESH_TAG_GRID",
  GET_TAG_LIST_START: "GET_TAG_LIST_START",
  GET_TAG_LIST_FULFILLED: "GET_TAG_LIST_FULFILLED",
  GET_TAG_LIST_FAILED: "GET_TAG_LIST_FAILED",
  UPDATE_SELECTED_TAGS_LIST: 'UPDATE_SELECTED_TAGS_LIST',
  UPDATE_COLUMN_SETTING: 'UPDATE_COLUMN_SETTING',
  TAG_COLUMN_OPTIONS_LOADING_START: 'TAG_COLUMN_OPTIONS_LOADING_START',
  TAG_COLUMN_OPTIONS_LOADING_STOP: 'TAG_COLUMN_OPTIONS_LOADING_STOP',
  TAG_UPDATED: 'TAG_UPDATED',
  TAG_UPDATING: 'TAG_UPDATING',

  //UPGRADE
  UPGRADE_TAGS_SUCCESS: "UPGRADE_TAGS_SUCCESS",

  //project detial list action types
  SAVETEMPLATE_START: 'SAVETAG_START',
  SAVETEMPLATE_FULFILLED: 'SAVETAG_FULFILLED',
  SAVETEMPLATE_FAILED: 'SAVETAG_FAILED',

  GENERATE_REPORT_START: "GENERATE_REPORT_START",
  GENERATE_REPORT_FULFILLED: 'GENERATE_REPORT_FULFILLED',
  GENERATE_REPORT_FAILED: 'GENERATE_REPORT_FAILED',

  //edit project details
  EDITTAG_START: 'EDITTAG_START',
  EDITTAG_FULFILLED: 'EDITTAG_FULFILLED',
  EDITTAG_FAILED: 'EDITTAG_FAILED',

  //cso export 
  CSOEXPORTDIALOUGE_ISOPEN: 'CSOEXPORTDIALOUGE_ISOPEN',

  //cso calculation
  CSO_CALCULATION_START: "CSO_CALCULATION_START",
  CSO_CALCULATION_FULFILLED: 'CSO_CALCULATION_FULFILLED',
  CSO_CALCULATION_FAILED: 'CSO_CALCULATION_FAILED',
  CSO_CALCULATION_RESET: "CSO_CALCULATION_RESET",

  //Save Tag Template NAO
  SAVE_TAG_TEMPLATE_START: 'SAVE_TAG_TEMPLATE_START',
  SAVE_TAG_TEMPLATE_FULFILLED: 'SAVE_TAG_TEMPLATE_FULFILLED',
  SAVE_TAG_TEMPLATE_FAILED: 'SAVE_TAG_TEMPLATE_FAILED',

  // Get tag templates NAO
  GET_TAG_TEMPLATE_START: 'GET_TAG_TEMPLATE_START',
  GET_TAG_TEMPLATE_FULFILLED: 'GET_TAG_TEMPLATE_FULFILLED',
  GET_TAG_TEMPLATE_FAILED: 'GET_TAG_TEMPLATE_FAILED',

  //Delete tag templates NAO
  DELETE_TAGTEMPLATE_FULFILLED: "DELETE_TAGTEMPLATE_FULFILLED",

  //Update tag templates
  UPDATE_TAG_TEMPLATE_FULFILLED: "UPDATE_TAG_TEMPLATE_FULFILLED",
  UPDATE_TAG_TEMPLATE_START: "UPDATE_TAG_TEMPLATE_START",
  UPDATE_TAG_TEMPLATE_FAILED: "UPDATE_TAG_TEMPLATE_FAILED",

  //Get concept templates
  GET_CONCEPT_TEMPLATE_START: 'GET_CONCEPT_TEMPLATE_START',
  GET_CONCEPT_TEMPLATE_FULFILLED: 'GET_CONCEPT_TEMPLATE_FULFILLED',
  GET_CONCEPT_TEMPLATE_FAILED: 'GET_CONCEPT_TEMPLATE_FAILED',

  //DELETE concept templates
  DELETE_CONCEPT_TEMPLATE_FULFILLED: 'DELETE_CONCEPT_TEMPLATE_FULFILLED',

  //TagTemplate dialouge constants
  OPEN_SAVE_POPUP: "OPEN_SAVE_POPUP",
  OPEN_DIALOUGE: "OPEN_DIALOUGE",
  OPEN_DELETE_DIALOUGE: "OPEN_DELETE_DIALOUGE",
  OPEN_REPLACE_DIALOUGE: "OPEN_REPLACE_DIALOUGE",
  TAG_DATA: "TAG_DATA",

  //Set Builder Permission
  BUILDER_PERMISSIONS_SET: "BUILDER_PERMISSIONS_SET",

  //Update User Profile
  UPDATE_USER_PROFILE: 'UPDATE_USER_PROFILE',

  //Selection Load NA
  GET_INITIAL_SELECTION_LOADING: "GET_INITIAL_SELECTION_LOADING",
  GET_INITIAL_SELECTION_LOADED: "GET_INITIAL_SELECTION_LOADED",
  SET_DEFAULT_SELECTION_LOAD: "SET_DEFAULT_SELECTION_LOAD",

  //Configuartion Load NA
  GET_INITIAL_CONFIGURATION_LOADING: "GET_INITIAL_CONFIGURATION_LOADING",
  GET_INITIAL_CONFIGURATION_LOADED: "GET_INITIAL_CONFIGURATION_LOADED",
  SET_DEFAULT_CONFIGURATION_LOAD: "SET_DEFAULT_CONFIGURATION_LOAD",


  //Release Notes
  FETCH_RELEASE_NOTES_FULFILLED: "FETCH_RELEASE_NOTES_FULFILLED",
  FETCH_RELEASE_NOTES_FAILED: "FETCH_RELEASE_NOTES_FAILED",
  CLOSE_RELEASE_NOTES_FULFILLED: "CLOSE_RELEASE_NOTES_FULFILLED",
  CLOSE_RELEASE_NOTES_FAILED: "CLOSE_RELEASE_NOTES_FULFILLED",
  HIDE_RELEASE_NOTES: "HIDE_RELEASE_NOTES",
  BUILDERS_PERMISSIONS: "Builders Permissions",

  //Report Types
  FULL_LOAD: "Full Load",
  IPLV: "IPLV",
  NPLV: "NPLV",
  LOAD_LINE: "Load Line",
  COMPRESSOR_MAP: "Compressor Map",
  COMPRESSOR_MAPS: "Compressor Maps",

  YES: "Y",
  TRUE: "TRUE",
  FALSE: "FALSE",

  SORT_DIRECTION: "desc", //asc or desc

  LOCALE_UPDATE_USER_ROLES: "LOCALE_UPDATE_USER_ROLES", //update user roles array

  UPGRADE_START: "UPGRADE_START", //bulk upgrade start
  UPGRADE_RESET: "UPGRADE_RESET", //on bulk upgrade close

  LOCK_ID_UPDATE: "LOCK_ID_UPDATE", //Update locked tag id
  LOCK_ID_UPDATE_WITH_WARNING: "LOCK_ID_UPDATE_WITH_WARNING", //Update locked tag id with warning

};